update asserts with raise+error
obss/sahi pull request #495
Opened 2022-06-17 22:24 UTC by kadirnar

fixed https://github.com/obss/sahi/issues/492

Coco.py dosyası için güncelleme yapılmıştır. Kontrol edip geri dönüş yapabilir misiniz? Bu format doğruysa diğer dosyaları bu şekilde güncelleyeceğim. @fcakyon

2022-06-17 22:25 UTC, fcakyon commented on sahi/utils/coco.py
> +        if bbox is not None or segmentation is not None:  #  Check if this is correct
```suggestion
        if bbox is None and segmentation is None:
```

2022-06-17 22:26 UTC, fcakyon commented on sahi/utils/coco.py
> +            raise NotImplementedError("bbox or segmentation is not supported")
```suggestion
            raise ValueError("you must provide a bbox or polygon"")
```

2022-06-17 22:27 UTC, fcakyon commented on sahi/utils/coco.py
> +            raise ValueError("image_id_setting must be either auto or manual")
```suggestion
            raise ValueError("image_id_setting must be either 'auto' or 'manual'")
```

2022-06-17 22:31 UTC, fcakyon commented on sahi/utils/coco.py
>          if self.image_id_setting == "manual":
```python
        if self.image_id_setting == "manual" and image.id is None:
            raise ValueError("image id should be manually set for image_id_setting='manual'")
        self.images.append(image)
```

2022-06-17 22:32 UTC, fcakyon commented on sahi/utils/coco.py
> +        if self.image_dir and coco.image_dir:
```suggestion
        if self.image_dir is None or coco.image_dir is None:
```

2022-06-17 22:33 UTC, fcakyon commented on sahi/utils/coco.py
> +        if type(video) == CocoVideo:
```suggestion
        if type(video) != CocoVideo:
```

2022-06-17 22:34 UTC, fcakyon commented on sahi/utils/coco.py
> +        if type(category) == CocoCategory:
```suggestion
        if type(category) != CocoCategory:
```

2022-06-17 22:34 UTC, fcakyon commented on sahi/utils/coco.py
> +            if coco_image_dir is not None:
```suggestion
            if coco_image_dir is None:
```

2022-06-17 22:36 UTC, fcakyon commented on sahi/utils/coco.py
> +        if type(coco_dict_or_path) == str or type(coco_dict_or_path) == dict:
```suggestion
        if type(coco_dict_or_path) not in [list, dict]:
```

2022-06-17 22:36 UTC, fcakyon commented on sahi/utils/coco.py
> +            raise ValueError("coco_dict_or_path should be list of dict or str")
```suggestion
            raise TypeError("coco_dict_or_path should be a dict or str")
```

2022-06-17 22:37 UTC, fcakyon commented on sahi/utils/coco.py
> +            raise Exception("category must be a CocoCategory instance")
```suggestion
            raise TypeError("category must be a CocoCategory instance")
```

2022-06-17 22:37 UTC, fcakyon commented on sahi/utils/coco.py
> +            raise Exception("video must be a CocoVideo instance")
```suggestion
            raise TypeError("video must be a CocoVideo instance")
```

2022-06-17 22:37 UTC, fcakyon commented on sahi/utils/coco.py
> +            raise Exception("video must be a CocoVideo instance")
```suggestion
            raise TypeError("video must be a CocoVideo instance")
```

2022-06-17 22:38 UTC, fcakyon requested changes
and/or/not/== logic'lerini biraz daha dikkatli dusunmen gerekiyor @kadirnar :)

2022-06-17 23:21 UTC, kadirnar commented
Assert çıktılarını alamadığım için tahmine dayalı kod yazmıştım. Düzeltmeleri referans alarak düzeltmelere devam edeceğim.

2022-06-17 23:47 UTC, fcakyon commented on sahi/utils/coco.py
> +        if type(coco_dict_or_path) not in [list, dict]:
```suggestion
        if type(coco_dict_or_path) not in [str, dict]:
```

2022-06-18 10:24 UTC, fcakyon commented on sahi/utils/coco.py
> +        if type(coco_dict_or_path) not in [list, dict]:
@kadirnar

2022-06-18 13:04 UTC, fcakyon commented
@kadirnar son merge conflicti fixledim, branchin son halini pullayarak devam edebilirsin calismalarina 👍

2022-06-18 13:07 UTC, kadirnar commented
> 

Eğer kodlar da problem yoksa güncel halini pull yapıp PR açıyorum.

2022-06-18 13:08 UTC, fcakyon commented on sahi/utils/mot.py
> +                raise TypeError("to_norfair_trackedobjects() requires annotation.track_id to be set.")
```suggestion
                raise ValueError("to_norfair_trackedobjects() requires annotation.track_id to be set.")
```

2022-06-18 13:08 UTC, fcakyon commented on sahi/utils/mot.py
> +            raise TypeError(f"'type' can be one of ['gt', 'det'], you provided: {type}")
```suggestion
            raise ValueError(f"'type' can be one of ['gt', 'det'], you provided: {type}")
```

2022-06-18 13:08 UTC, fcakyon commented on sahi/utils/coco.py
> +    # prepare image info from- coco dataset
```suggestion
    # prepare image info from coco dataset
```

2022-06-18 13:11 UTC, fcakyon commented on sahi/annotation.py
> +        if isinstance(id, int):
```suggestion
        if not isinstance(id, int):
```

2022-06-18 13:11 UTC, fcakyon commented on sahi/annotation.py
> +        if isinstance(name, str):
```suggestion
        if not isinstance(name, str):
```

2022-06-18 13:13 UTC, fcakyon commented
> > 
> 
> Eğer kodlar da problem yoksa güncel halini pull yapıp PR açıyorum.

Bazi eksikler var ama yeni PR'da devam edebilirsin onlara 👍

2022-06-18 13:13 UTC, kadirnar commented on sahi/utils/mot.py
> +            raise TypeError(f"'type' can be one of ['gt', 'det'], you provided: {type}")
Burada type ilgili hata veriyor. TypeError olması gerekmiyor mu?

2022-06-18 13:16 UTC, fcakyon commented on sahi/utils/mot.py
> +            raise TypeError(f"'type' can be one of ['gt', 'det'], you provided: {type}")
Python'daki TypeError degisken veya class turleri ile ilgili hatalarda veriliyor, str, int veya class turunden hatalar icin yani.

Bu satirdaki hata degiskenin aldigi bir degerle ilgili, o yuzden ValueError daha dogru olur. Fonksiyonda kullanilan type degiskeni seni yaniltmasin, o degiskenin adinin ne oldugunun bir onemi yok hata verirken.

2022-06-18 15:54 UTC, kadirnar commented
Bu PR https://github.com/obss/sahi/pull/499 'a taşınmıştır

2022-06-18 15:54 UTC, closed without merging