ONNX runtime support
obss/sahi pull request #922
Opened 2023-07-28 11:27 UTC by karl-joan

Made changes to pull request #904 since the author didn't respond.

Changes:
- Separated functions for image preprocessing and post-processing.
- You can supply options to `onnxruntime`.
- Fixed bugs in image post-processing, where `iou_threshold` was missing and bounding boxes were sent to `non_max_supression` in wrong format.
- Fixed bug where sessions options weren't passed to `onnxruntime`
- Added some test
- Renamed `onnx.py` to `onnx_model.py` to avoid confusion with `onnx` library.

The code was designed with the intention of being used for YOLOv8 ONNX model. Perhaps some changes should be made to make it more suitable for other architectures.

2023-08-04 11:18 UTC, karl-joan commented
@julled You can go ahead and test it

2023-08-04 14:52 UTC, LongLe18 commented
@karl-joan I tested your contribute. It's appear error like image below. And image which I used to test (https://ultralytics.com/images/bus.jpg)
![image](https://github.com/obss/sahi/assets/53988728/1c584eec-ca53-4413-9796-835b582af4e4)

2023-08-06 07:35 UTC, karl-joan commented
@LongLe18 The test is meant to be run with image specified in the test file. If you change the image, then it won't work since the image you provided does not contain any cars.

If you just want to try the model, then use one of the built in functions such as `get_sliced_prediction` or `get_prediction`.

2023-08-07 00:01 UTC, LongLe18 commented
@karl-joan  ok tks sir. I understood, you have not handled except yet. I will try again

2023-11-05 22:21 UTC, fcakyon commented
Thanks a lot for this amazing contribution @karl-joan !

If you could add a demo notebook as other model implementations, we would gladly merge the PR 👍

2023-11-05 23:25 UTC, fcakyon requested changes
code styling errors need to be fixed, a demo notebook need to be added

2023-11-06 09:06 UTC, fcakyon commented on requirements.txt
> +onnxruntime
it should not be a core dependency

```suggestion
```

2023-11-06 09:08 UTC, fcakyon commented on sahi/auto_model.py
> +    "onnx_model": "ONNXDetectionModel"
```suggestion
    "yolov8onnx": "Yolov8OnnxDetectionModel"
```

2023-11-06 09:08 UTC, fcakyon commented on sahi/models/__init__.py
> +from . import base, detectron2, huggingface, mmdet, onnx_model, torchvision, yolonas, yolov5
```suggestion
from . import base, detectron2, huggingface, mmdet, yolov8onnx, torchvision, yolonas, yolov5
```

2023-11-06 09:08 UTC, fcakyon commented on sahi/models/onnx_model.py
> +class ONNXDetectionModel(DetectionModel):
```suggestion
class Yolov8OnnxDetectionModel(DetectionModel):
```

2023-11-06 09:09 UTC, fcakyon commented on tests/test_onnxmodel.py
> +class TestONNXDetectionModel(unittest.TestCase):
```suggestion
class TestYolov8OnnxDetectionModel(unittest.TestCase):
```

2023-11-06 09:10 UTC, fcakyon commented on tests/test_onnxmodel.py
> +        from sahi.models.onnx_model import ONNXDetectionModel
```suggestion
        from sahi.models.yolov8onnx import Yolov8OnnxDetectionModel
```

2023-11-06 16:26 UTC, fcakyon commented
@karl-joan can you please fix the styling? https://github.com/obss/sahi#contributing

2023-11-06 20:08 UTC, karl-joan commented
@fcakyon  Yes, I'll try to get that and the notebook tomorrow done.

2023-11-07 16:03 UTC, karl-joan commented
@fcakyon Let me know if you need anything else.

2024-01-09 12:46 UTC, devrimcavusoglu commented
@karl-joan @fcakyon what is the status here ? I can take the lead, but I assume code formatting/linting has been addressed. As far as I reviewed the files, there are no additional requirements.

2024-01-10 09:08 UTC, karl-joan commented
@devrimcavusoglu It's currently waiting behind @fcakyon

2024-01-10 09:24 UTC, devrimcavusoglu approved these changes
LGTM!

2024-01-10 09:28 UTC, merged